### ISSUE TITLE
ValueError: conflicting sizes for dimension 'lat': length 1 on the data but length 768 on coordinate 'lat' when calling cgnet.predict

### ISSUE THREAD

**Issue by paulbnder** [andregraubner/ClimateNet#8]
I am trying to run example.py but get an error when I call cgnet.run in line 27. This is the trace:

Traceback (most recent call last):
  File "example.py", line 27, in <module>
    class_masks = cgnet.predict(inference) # masks with 1==TC, 2==AR
  File "/informatik1/students/home/9bender/Bachelorarbeit/ClimateNet/climatenet/models.py", line 121, in predict
    predictions.append(xr.DataArray(preds, coords=coords, dims=coords, attrs=batch.attrs))
  File "/informatik1/students/home/9bender/Bachelorarbeit/ENTER/envs/climatenet/lib/python3.8/site-packages/xarray/core/dataarray.py", line 403, in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
  File "/informatik1/students/home/9bender/Bachelorarbeit/ENTER/envs/climatenet/lib/python3.8/site-packages/xarray/core/dataarray.py", line 152, in _infer_coords_and_dims
    raise ValueError(
ValueError: conflicting sizes for dimension 'lat': length 1 on the data but length 768 on coordinate 'lat'

I am using data from the link provided in the readme for inference. Is this a known issue?

**Comment by paulbnder** [comment]
Hi Andre, thank you so much for providing the fix. Now it works!
